# Form implementation generated from reading ui file 'd:\Python_PORTFOLIO\9_Register_sign_in_form_pyqt6\App_logged_in\UI\logged.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mw_logged_in(object):
    def setupUi(self, mw_logged_in):
        mw_logged_in.setObjectName("mw_logged_in")
        mw_logged_in.resize(573, 334)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        mw_logged_in.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mw_logged_in)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lb_main_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_main_logo.setText("")
        self.lb_main_logo.setPixmap(QtGui.QPixmap(":/buttons/logo_white_thumb.png"))
        self.lb_main_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_main_logo.setObjectName("lb_main_logo")
        self.verticalLayout.addWidget(self.lb_main_logo)
        self.lb_main_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_main_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_main_title.setObjectName("lb_main_title")
        self.verticalLayout.addWidget(self.lb_main_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        mw_logged_in.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mw_logged_in)
        self.statusbar.setObjectName("statusbar")
        mw_logged_in.setStatusBar(self.statusbar)

        self.retranslateUi(mw_logged_in)
        QtCore.QMetaObject.connectSlotsByName(mw_logged_in)

    def retranslateUi(self, mw_logged_in):
        _translate = QtCore.QCoreApplication.translate
        mw_logged_in.setWindowTitle(_translate("mw_logged_in", "Logged_in_window"))
        self.lb_main_title.setText(_translate("mw_logged_in", "->> WELCOME INSIDE <<-"))
